# Generated by Django 6.0 on 2025-12-25 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotsCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('robots_txt', models.TextField()),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('is_scrapable', models.BooleanField(default=True)),
                ('crawl_delay', models.IntegerField(default=0)),
                ('disallowed_paths', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='HarvestJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('options', models.JSONField(default=dict)),
                ('priority', models.IntegerField(choices=[(1, 'Urgent'), (5, 'Normal'), (10, 'Low')], default=5)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('error_message', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('cron_schedule', models.CharField(blank=True, max_length=100)),
                ('parent_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.harvestjob')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HarvestAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Job Created'), ('started', 'Job Started'), ('completed', 'Job Completed'), ('failed', 'Job Failed'), ('downloaded', 'Result Downloaded'), ('deleted', 'Job Deleted')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.harvestjob')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HarvestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('html', models.TextField(blank=True)),
                ('structured_data', models.JSONField(default=dict)),
                ('assets', models.JSONField(default=list)),
                ('total_assets', models.IntegerField(default=0)),
                ('total_size', models.BigIntegerField(default=0)),
                ('technologies', models.JSONField(default=dict)),
                ('frontend_framework', models.CharField(blank=True, max_length=50)),
                ('css_framework', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('links', models.JSONField(default=dict)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to='harvests/zips/')),
                ('json_export', models.FileField(blank=True, null=True, upload_to='harvests/json/')),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='core.harvestjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('button', 'Button'), ('card', 'Card'), ('navbar', 'Navigation Bar'), ('footer', 'Footer'), ('form', 'Form'), ('modal', 'Modal'), ('other', 'Other')], max_length=50)),
                ('html', models.TextField()),
                ('css', models.TextField(blank=True)),
                ('js', models.TextField(blank=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='components/screenshots/')),
                ('usage_count', models.IntegerField(default=1)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.harvestresult')),
            ],
            options={
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('css', 'CSS'), ('js', 'JavaScript'), ('font', 'Font'), ('video', 'Video'), ('other', 'Other')], max_length=20)),
                ('file_path', models.FileField(upload_to='harvests/assets/')),
                ('file_size', models.BigIntegerField()),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('load_time', models.FloatField(blank=True, null=True)),
                ('is_critical', models.BooleanField(default=False)),
                ('is_lazy_loaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_details', to='core.harvestresult')),
            ],
            options={
                'ordering': ['asset_type', '-file_size'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_summary', models.TextField()),
                ('architecture_analysis', models.TextField()),
                ('component_list', models.JSONField(default=list)),
                ('accessibility_score', models.FloatField(blank=True, null=True)),
                ('seo_score', models.FloatField(blank=True, null=True)),
                ('performance_score', models.FloatField(blank=True, null=True)),
                ('seo_suggestions', models.JSONField(default=list)),
                ('accessibility_issues', models.JSONField(default=list)),
                ('security_warnings', models.JSONField(default=list)),
                ('tech_stack_summary', models.TextField()),
                ('similar_sites', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='core.harvestresult')),
            ],
        ),
        migrations.CreateModel(
            name='HarvestSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('changes_detected', models.BooleanField(default=False)),
                ('diff_summary', models.JSONField(default=dict)),
                ('diff_details', models.TextField(blank=True)),
                ('added_elements', models.JSONField(default=list)),
                ('removed_elements', models.JSONField(default=list)),
                ('modified_elements', models.JSONField(default=list)),
                ('tech_changes', models.JSONField(default=dict)),
                ('original_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.harvestresult')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lighthouse_score', models.JSONField(default=dict)),
                ('performance_score', models.IntegerField(null=True)),
                ('accessibility_score', models.IntegerField(null=True)),
                ('best_practices_score', models.IntegerField(null=True)),
                ('seo_score', models.IntegerField(null=True)),
                ('largest_contentful_paint', models.FloatField(null=True)),
                ('first_input_delay', models.FloatField(null=True)),
                ('cumulative_layout_shift', models.FloatField(null=True)),
                ('time_to_interactive', models.FloatField(null=True)),
                ('total_blocking_time', models.FloatField(null=True)),
                ('total_load_time', models.FloatField()),
                ('dom_content_loaded', models.FloatField(null=True)),
                ('first_contentful_paint', models.FloatField(null=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('total_transfer_size', models.BigIntegerField(default=0)),
                ('resource_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='core.harvestresult')),
            ],
        ),
        migrations.AddIndex(
            model_name='harvestjob',
            index=models.Index(fields=['status', '-created_at'], name='core_harves_status_3f977c_idx'),
        ),
        migrations.AddIndex(
            model_name='harvestjob',
            index=models.Index(fields=['user', '-created_at'], name='core_harves_user_id_07e69f_idx'),
        ),
    ]
